// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPfjFED71BOBeNid31YSUgGRev9okGS4',
    appId: '1:804805311424:web:861e227813218d9600a625',
    messagingSenderId: '804805311424',
    projectId: 'kodularbfelecdrawings',
    authDomain: 'kodularbfelecdrawings.firebaseapp.com',
    databaseURL: 'https://kodularbfelecdrawings.firebaseio.com',
    storageBucket: 'kodularbfelecdrawings.appspot.com',
    measurementId: 'G-JYF9ZNTQS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXI_zLCifMqULVOD3sswL2akUJpdVDjsw',
    appId: '1:804805311424:android:2b4e416aa621e1de00a625',
    messagingSenderId: '804805311424',
    projectId: 'kodularbfelecdrawings',
    databaseURL: 'https://kodularbfelecdrawings.firebaseio.com',
    storageBucket: 'kodularbfelecdrawings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KN8Z2q9JzbGRAjdUzh9f3H-X1DLAi8w',
    appId: '1:804805311424:ios:d32b73a4e18807ea00a625',
    messagingSenderId: '804805311424',
    projectId: 'kodularbfelecdrawings',
    databaseURL: 'https://kodularbfelecdrawings.firebaseio.com',
    storageBucket: 'kodularbfelecdrawings.appspot.com',
    iosBundleId: 'com.example.bfElecApps',
  );
}
